---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(corrplot)
library(FactoMineR)
library(factoextra)
library(readr)
library(reshape2)
library(gridExtra)
```

```{r}
US_data <- read_csv("US_data2.csv")
California_data <- read_csv("California_data.csv")
Texas_data <- read_csv("Texas_data.csv")
Illinois_data <- read_csv("Illinois_data.csv")
```

```{r}
#On garde uniquement les valeurs numériques
Texas_num  <- Texas_data[,c(3:34)]

par(cex.main=2, cex.lab=2, cex.axis=2)

m_corr = cor(Texas_num,use="complete.obs")
corrplot(m_corr,method="ellipse", order="hclust",tl.col="blue",tl.srt=55, 
         addCoef.col ="black", cl.cex=1.0, addCoefasPercent = TRUE, number.cex = 0.6,
         tl.cex = 0.3, type = "upper")

```

```{r}
acp <- PCA(Texas_num, scale.unit = TRUE, graph = FALSE)

g1 <- fviz_eig(acp, addlabels = TRUE, ylim = c(0,40))
g2 <- ggplot(melt(acp$ind$coord), aes(x=Var2,y=value))+geom_boxplot()+xlab("")
grid.arrange(g1,g2,ncol=2)
```

```{r}

```

```{r}

```

```{r}

```


